name: workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.8
        ports:
          - 4222:4222
          - 6222:6222
          - 8222:8222

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # downloads a copy of repository
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Build jar
        run: mvn package -Dmaven.test.skip=true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-chat:latest
